### Harmeet Singh | IIT Kharagpur
### Decision tree classifier

In [2]:
# IMPORT LIBRARIES
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [3]:
# IMPORT DATASET

In [11]:
balance_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-'+
'databases/balance-scale/balance-scale.data', sep = ',', header = None)

In [12]:
print(balance_data.head())

   0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5


In [14]:
# SPLIT THE DATASET INTO TRAIN AND TEST

X = balance_data.values[:, 1:5]
Y = balance_data.values[:, 0]

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100)

In [17]:
# TRAIN THE MDOEL WITH "GINI INDEX"

clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100, max_depth = 3, min_samples_leaf = 5)

clf_gini.fit(x_train, y_train)


DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=100)

In [19]:
# TRAIN THE MODEL WITH "INFORMATION GAIN"

clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100, max_depth = 3, min_samples_leaf = 5)

clf_entropy.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=100)

In [22]:
# PREDICTIONS

# ENTROPY
y_pred_entropy = clf_entropy.predict(x_test)

# GINI INDEX
y_pred_gini = clf_gini.predict(x_test)

print(y_pred_entropy)
print('---------------')
print(y_pred_gini)

['R' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L'
 'L' 'R' 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'L' 'L'
 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'L'
 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'R' 'R' 'L' 'R' 'L'
 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'R' 'R' 'R' 'R' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L'
 'L' 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R'
 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'L' 'R'
 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'R']
---------------
['R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'L'
 'L' 'R' 'L' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L'
 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'R'
 

In [26]:
# CONFUSION MATRIX

print('Confusion Matrix Entropy:')
print(confusion_matrix(y_test, y_pred_entropy))
print('Confusion Matrix Gini Index:' )
print(confusion_matrix(y_test, y_pred_gini))

Confusion Matrix Entropy:
[[ 0  6  7]
 [ 0 63 22]
 [ 0 20 70]]
Confusion Matrix Gini Index:
[[ 0  6  7]
 [ 0 67 18]
 [ 0 19 71]]


In [27]:
# ACCURACY

print('Accuracy - entropy:')
print(accuracy_score(y_test, y_pred_entropy))
print('Accuracy - Gini Index:')
print(accuracy_score(y_test, y_pred_gini))

Accuracy - entropy:
0.7074468085106383
Accuracy - Gini Index:
0.7340425531914894
